# Generated by Django 3.2 on 2024-11-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default='user', max_length=10, verbose_name='Роль'),
        ),
    ]
