# Generated by Django 3.2 on 2024-11-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'default_related_name': 'titles', 'ordering': ('-year',), 'verbose_name': 'произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
